package:
  name: menpo3d
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo 0.5.*
    - cyassimp 0.2.*
    - cyrasterize 0.2.*
    - menpo-pyvrml97 2.3.0a4  # [py2k]
    - mayavi 4.4.*  # [py2k]

test:
  requires:
  - nose
  - mock

  imports:
  - menpo3d

about:
  home: https://github.com/menpo/menpo3d/
  license: BSD
