package:
  name: menpo3d
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo *
    - cyassimp >=1.0.0,<2.0.0
    - cyrasterize >=0.2.4,<0.3
    - menpo-pyvrml97 2.3.0a4  # [py2k]
    - mayavi 4.4.*  # [py2k]

test:
  requires:
  - nose
  - mock 1.0.1

  imports:
  - menpo3d

about:
  home: https://github.com/menpo/menpo3d/
  license: BSD
